import pandas as pd
import sqlalchemy
from datetime import datetime
import os

DB_URL = os.getenv("BMS_DB_URL", "postgresql+psycopg2://bms:bms_pass@localhost:5432/bms_db")
CSV_PATH = os.getenv("EP_CSV", "energyplus/output.csv")  # path to csv generated by EnergyPlus

def ingest(csv_path=CSV_PATH):
    engine = sqlalchemy.create_engine(DB_URL)
    df = pd.read_csv(csv_path)
    # Expecting CSV to have columns: Date/Time, OutdoorDryBulb, Zone Air Temp, HVAC Power
    # If your EnergyPlus CSV uses different names, update these column names mappings accordingly.
    df = df.rename(columns={
        'Date/Time':'Date/Time',
        'OutdoorDryBulb':'outdoor_temp',
        'Zone Mean Air Temperature':'zone_air_temp',
        'HVAC Power':'hvac_power'
    })
    # create a timestamp column (EnergyPlus usually uses "Date/Time" like 01/01 00:00:00)
    df['ts'] = pd.to_datetime(df['Date/Time'], errors='coerce', infer_datetime_format=True)
    # map other fields
    df['zone_name'] = 'Zone 1'
    df = df[['ts', 'zone_name', 'outdoor_temp', 'zone_air_temp', 'hvac_power']].dropna(subset=['ts'])
    df.to_sql('energyplus_timeseries', engine, if_exists='append', index=False)
    print(f"Inserted {len(df)} rows into energyplus_timeseries")

if __name__ == "__main__":
    ingest()
